3번쨰 피드백 요청 - PR
cheeryFeed/cherry-feed-server pull request #4
Opened 2023-04-06 10:37 UTC by kwakchiyoung

3번쨰 피드백 요청 - PR

2023-04-06 11:39 UTC, cousim46 requested changes
고생하셨습니다 리뷴 남겼습니다 확인해주시고 확인된 내용은 이모티콘 처리해주세요

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/account/domain/SocialLogin.java
>      private Long createdById;   //유저아이디
이 createdById는 무엇일까요?

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/account/domain/WithdrawalDetail.java
>      private Long status;        //탈퇴사유 1,2,3,4,5
이 부분도 ENUM으로 관리하는게 좋을거 같아요~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/couple/domain/Couple.java
>      @OneToMany(mappedBy = "couple")  //FK가 없는쪽에 mappedBy를 써주는것이 좋다.
A라는 사용자가 두 커플 또는 세 커플 즉 여러 커플로 저장될 수 있나요?

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/Love.java
>      private Account createdById;
이 부분도 변수명 변경해주시면 좋을거 같아요 ㅎㅎ

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/Post.java
>      private Account createdById;
이 부분도 변수명 수정해주세요~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/Post.java
>      private CoupleCalendar calId;
이 부분도 변수명 수정해주세요 ~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/ReportUser.java
> +    private int dctStts;               //신고유형
신고유형에는 무엇이 있을까요?

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/ReportUser.java
>      private Post postNo;
이 부분도 변수명 수정해주세요 ~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/account/domain/Account.java
>      private WithdrawalDetail withdrawalDetailId;
이 부분도 변수명 수정해주세요 ~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/calendar/domain/CoupleCalendar.java
> +    private int type;           //유형 - 계획1,일정2
ENUM으로 관리하는게 좋을거 같습니다!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/calendar/domain/CoupleCalendar.java
>      private Account createdById;
이 부분도 변수명 수정해주세요 ~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/Love.java
>      private Post createdByNo;
이 부분도 변수명 수정해주세요 ~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/apps/post/domain/ReportUser.java
>      private CoupleCalendar createdById;
이 부분도 변수명 수정해주세요 ~!

2023-04-06 11:39 UTC, cousim46 commented on src/main/java/com/bazzi/cherryfeed/exception/ExceptionManager.java
>      @ExceptionHandler(RuntimeException.class)
저번 리뷰때도 남겼던 내용인데 RuntimeException이 발생할경우 무조건 409(CONFLICT) 상태코드를 반환하는것인가요? 만약 의도하신거면 이유가 궁금합니다!

2023-04-06 12:18 UTC, kwakchiyoung commented
> 
빠르게 답변주셔서 감사합니다..! 도움이 정말 많이 되고있어요 ㅠㅠ 혹시 저번에 리뷰 달아주셨던곳에 추가 질문달아놨는데 혹시 한번만 확인 부탁드릴 수 있을까요 ,,,? master에 커밋한 부분이요!

2023-04-06 12:19 UTC, kwakchiyoung commented
> 고생하셨습니다 리뷴 남겼습니다 확인해주시고 확인된 내용은 이모티콘 처리해주세요 해결된 리뷰들은Resolve conversation 눌러주세요~

빠르게 답변주셔서 감사합니다..! 도움이 정말 많이 되고있어요 ㅠㅠ 혹시 저번에 리뷰 달아주셨던곳에 추가 질문달아놨는데 혹시 한번만 확인 부탁드릴 수 있을까요 ,,,? master에 커밋한 부분이요!

2023-04-07 04:43 UTC, cousim46 reviewed
질문 남기셨던거 리뷰 달아놨습니다!

2023-04-10 12:00 UTC, kwakchiyoung commented on src/main/java/com/bazzi/cherryfeed/apps/couple/domain/Couple.java
>      @OneToMany(mappedBy = "couple")  //FK가 없는쪽에 mappedBy를 써주는것이 좋다.
아니요 불가능합니다..

2023-04-10 12:05 UTC, kwakchiyoung commented on src/main/java/com/bazzi/cherryfeed/exception/ExceptionManager.java
>      @ExceptionHandler(RuntimeException.class)
저부분은 지우겠습니다!

2023-04-10 12:45 UTC, kwakchiyoung commented
감사합니다 클로스 커밋 누른 후 다시 올리도록 할게요!

2023-04-10 12:45 UTC, closed without merging